services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: daov2
    ports:
      - "27017:27017"
    command: mongod
    # volumes:
    #   - mongo-data:/data/db
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: product_master
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

